services:
  teams-cassandra:
    container_name: "teams-cassandra"
    image: "cassandra:3.11"
    ports:
      - "7000:7000"
      - "9042:9042"
  teams-service-1:
    container_name: "teams-service-1"
    image: "test/teams-service:latest"
    ports:
      - "8080:8080"
    environment:
      - APP_CASSANDRA_CONTACTPOINTS=teams-cassandra:9042
  teams-service-2:
    container_name: "teams-service-2"
    image: "test/teams-service:latest"
    ports:
      - "8081:8080"
    environment:
      - APP_CASSANDRA_CONTACTPOINTS=teams-cassandra:9042